config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"

  resources :top, only: :index
  resources :users, only: [:show, :edit, :update,:new ,:create]
  resources :schedules, only:[:show,:create,:destroy,:edit,:update]
  resources :schedule2s, only:[:create,:destroy,:edit,:update]

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  belongs_to :user
  belongs_to :top
end

app/models/schedule2.rb
class Schedule2 < ActiveRecord::Base
end

app/models/top.rb
class Top < ActiveRecord::Base

  has_many :schedules
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                      styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
                                      content_type: ["image/jpg","image/jpeg","image/png"]

has_many :schedules


  def full_profile?
    avatar? && family_name? && first_name? && day? && fav? && massage?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :text)
    end
end

app/controllers/schedule2s_controller.rb
class Schedule2sController < ApplicationController

def create
  Schedule2.create(schedule_params)
end

def destroy
  schedule2 = Schedule2.find(params[:id])
      if schedule2.user_id == current_user.id
        schedule2.destroy
      end
end

def edit
  @schedule2 = Schedule2.find(params[:id])
end

  def update
    schedule2 = Schedule2.find(params[:id])
    schedule2.update(schedule_params)
  end




private
    def schedule_params
      params.require(:schedule2).permit(:date, :t8, :t9, :t10, :t11, :t12, :t13, :t14, :t15, :t16, :t17, :t18, :t19, :t20, :t21, :t22, :t23, :t24).merge(user_id: current_user.id)
      #bindingpryで確認できる.createの下に記述
      # 入ってくるparams "utf8"=>"✓", "authenticity_token"=>"Ym5EA6PYcHyVvh1Rzy4dAn1/jgq7KfG6R0exxfXnqaDIFQrOYDYWliyqNYjxpt7dP5tdeDwIO7cIUUMaAlSHvg==", "tweet"=>{"name"=>"", "image"=>"", "text"=>"prison break"}, "commit"=>"送信"}
      #reqireでtweetキー以下のパラメーターを獲得できる({}の部分)
      #current_idはform_forでは入れれないからmergeで
    end



end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController


def create
  Schedule.create(schedule_params)
end

def destroy
  schedule = Schedule.find(params[:id])
      if schedule.user_id == current_user.id
        schedule.destroy
      end
end


def edit
  @schedule = Schedule.find(params[:id])
end

  def update
    schedule = Schedule.find(params[:id])
    schedule.update(schedule_params)
  end


    private
    def schedule_params
      params.require(:schedule).permit(:date, :t8, :t9, :t10, :t11, :t12, :t13, :t14, :t15, :t16, :t17, :t18, :t19, :t20, :t21, :t22, :t23, :t24).merge(user_id: current_user.id)
      #bindingpryで確認できる.createの下に記述
      # 入ってくるparams "utf8"=>"✓", "authenticity_token"=>"Ym5EA6PYcHyVvh1Rzy4dAn1/jgq7KfG6R0exxfXnqaDIFQrOYDYWliyqNYjxpt7dP5tdeDwIO7cIUUMaAlSHvg==", "tweet"=>{"name"=>"", "image"=>"", "text"=>"prison break"}, "commit"=>"送信"}
      #reqireでtweetキー以下のパラメーターを獲得できる({}の部分)
      #current_idはform_forでは入れれないからmergeで
    end






end

app/controllers/top_controller.rb
class TopController < ApplicationController


  def index
  @dates = Schedule.where(date: params[:keyword])
  @chart_data = {
     t8: @dates.sum(:t8),
     t9: @dates.sum(:t9),
     t10: @dates.sum(:t10),
     t11: @dates.sum(:t11),
     t12: @dates.sum(:t12),
     t13: @dates.sum(:t13),
     t14: @dates.sum(:t14),
     t15: @dates.sum(:t15),
     t16: @dates.sum(:t16),
     t17: @dates.sum(:t17),
     t18: @dates.sum(:t18),
     t19: @dates.sum(:t19),
     t20: @dates.sum(:t20),
     t21: @dates.sum(:t21),
     t22: @dates.sum(:t22),
     t23: @dates.sum(:t23)}

@dates2 = Schedule2.where(date: params[:keyword])
  @chart_data2 = {
     t8: @dates2.sum(:t8),
     t9: @dates2.sum(:t9),
     t10: @dates2.sum(:t10),
     t11: @dates2.sum(:t11),
     t12: @dates2.sum(:t12),
     t13: @dates2.sum(:t13),
     t14: @dates2.sum(:t14),
     t15: @dates2.sum(:t15),
     t16: @dates2.sum(:t16),
     t17: @dates2.sum(:t17),
     t18: @dates2.sum(:t18),
     t19: @dates2.sum(:t19),
     t20: @dates2.sum(:t20),
     t21: @dates2.sum(:t21),
     t22: @dates2.sum(:t22),
     t23: @dates2.sum(:t23)}
 end








end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users = User.find(params[:id])
    @schedule = Schedule.new
    @schedule2 = Schedule2.new
    @attend_dates = Schedule.where(user_id:current_user.id).order(date: :asc)
    @attend_dates2 = Schedule2.where(user_id:current_user.id).order(date: :asc)
  end




  def edit
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :avatar, :day, :fav, :massage)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/schedule2s_helper.rb
module Schedule2sHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigator.html.erb
<% if params[:controller] == 'top' %>
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <span class="title_panna">PANN<span class="red">A.</span>P</span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav", id="moji">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#massage">massage</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#now">now</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#style">style</a>
                    </li>
                    <li>
                        <%= link_to "mypage", user_path(current_user), id:"space" %>
                    </li>
                    <li>
                        <%= link_to "logout", destroy_user_session_path, method: :delete, id:"moji_white"%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Pan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Grayscale - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<%= render 'layouts/navigator' %>


<%= yield %>

</body>
</html>

app/views/schedule2s/create.html.erb
 <div class="create_all">
  <div class="send">
      <h3>横大路への参加投稿が完了しました</h3></br></br></br>
      <%= link_to "マイページに戻る", user_path(current_user) %>
  </div>
</div>

app/views/schedule2s/destroy.html.erb
 <div class="create_all">
  <div class="send">
      <h3>削除が完了しました</h3>
      <%= link_to "マイページに戻る", user_path(current_user) %>
  </div>
</div>

app/views/schedule2s/edit.html.erb
<!-- header -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">
                    <span class="title_panna">PANN<span class="red">A.</span>P</span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav", id="moji">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <%= link_to "logout", destroy_user_session_path, method: :delete, id:"moji_white"%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
  </div>
        <!-- /.container -->
</nav>

<!-- 詳細表示 -->
<div class="detail_area">

        <div class="reserved">
        <%= @schedule2.date %>の参加時間
        </div>
        <table class="demo02">
        <thead>
          <tr>
            <th>08:00</br><% if  @schedule2.t8  == 1 then %>○<% else %>×<% end %></th>
            <th>09:00</br><% if  @schedule2.t9  == 1 then %>○<% else %>×<% end %></th>
            <th>10:00</br><% if  @schedule2.t10  == 1 then %>○<% else %>×<% end %></th>
            <th>11:00</br><% if  @schedule2.t11  == 1 then %>○<% else %>×<% end %></th>
            <th>12:00</br><% if  @schedule2.t12  == 1 then %>○<% else %>×<% end %></th>
            <th>13:00</br><% if  @schedule2.t13  == 1 then %>○<% else %>×<% end %></th>
            <th>14:00</br><% if  @schedule2.t14  == 1 then %>○<% else %>×<% end %></th>
            <th>15:00</br><% if  @schedule2.t15  == 1 then %>○<% else %>×<% end %></th>
            <th>16:00</br><% if  @schedule2.t16  == 1 then %>○<% else %>×<% end %></th>
            <th>17:00</br><% if  @schedule2.t17  == 1 then %>○<% else %>×<% end %></th>
            <th>18:00</br><% if  @schedule2.t18  == 1 then %>○<% else %>×<% end %></th>
            <th>19:00</br><% if  @schedule2.t19  == 1 then %>○<% else %>×<% end %></th>
            <th>20:00</br><% if  @schedule2.t20  == 1 then %>○<% else %>×<% end %></th>
            <th>21:00</br><% if  @schedule2.t21  == 1 then %>○<% else %>×<% end %></th>
            <th>22:00</br><% if  @schedule2.t22  == 1 then %>○<% else %>×<% end %></th>
            <th>23:00</br><% if  @schedule2.t23  == 1 then %>○<% else %>×<% end %></th>

          </tr>
          </thead>
        </table>
        <div class="edit_time">参加時間を編集する</div>
                      <div class="row form">
                          <div class="col-lg-12">
                            <%= form_for @schedule2 do |f| %>
                             <div class="form-group">
                              <div class="time_table">
                                    <div class="court">
                                    <table class="demo02">
                                      <thead>
                                        <tr>
                                          <th>08:00</br><%= f.check_box :t8, placeholder: "stadium" %></th>
                                          <th>09:00</br><%= f.check_box :t9, placeholder: "stadium" %></th>
                                          <th>10:00</br><%= f.check_box :t10, placeholder: "stadium" %></th>
                                          <th>11:00</br><%= f.check_box :t11, placeholder: "stadium" %></th>
                                          <th>12:00</br><%= f.check_box :t12, placeholder: "stadium" %></th>
                                          <th>13:00</br><%= f.check_box :t13, placeholder: "stadium" %></th>
                                          <th>14:00</br><%= f.check_box :t14, placeholder: "stadium" %></th>
                                          <th>15:00</br><%= f.check_box :t15, placeholder: "stadium" %></th>
                                          <th>16:00</br><%= f.check_box :t16, placeholder: "stadium" %></th>
                                          <th>17:00</br><%= f.check_box :t17, placeholder: "stadium" %></th>
                                          <th>18:00</br><%= f.check_box :t18, placeholder: "stadium" %></th>
                                          <th>19:00</br><%= f.check_box :t19, placeholder: "stadium" %></th>
                                          <th>20:00</br><%= f.check_box :t20, placeholder: "stadium" %></th>
                                          <th>21:00</br><%= f.check_box :t21, placeholder: "stadium" %></th>
                                          <th>22:00</br><%= f.check_box :t22, placeholder: "stadium" %></th>
                                          <th>23:00</br><%= f.check_box :t23, placeholder: "stadium" %></th>

                                        </tr>
                                        </thead>
                                      </table>
                                      <div class="submit"><%= f.submit "送信", class: "btn btn-primary withripple" %></div>
                              </div>
                            <% end %>
                           </div>
                          </div>
                        </div>






</div>

app/views/schedule2s/update.html.erb
 <div class="create_all">
  <div class="send">
  <h3>時間の編集が完了しました</h3></br></br></br>
      <%= link_to "マイページに戻る", user_path(current_user) %>
  </div>
</div>

app/views/schedules/create.html.erb
 <div class="create_all">
  <div class="send">
  <h3>京都南への参加投稿が完了しました</h3></br></br></br>
      <%= link_to "マイページに戻る", user_path(current_user) %>
  </div>
</div>

app/views/schedules/destroy.html.erb
 <div class="create_all">
  <div class="send">
      <h3>削除が完了しました</h3>
      <%= link_to "マイページに戻る", user_path(current_user) %>
  </div>
</div>

app/views/schedules/update.html.erb
 <div class="update_all">
  <div class="send">
      <h3>時間の編集が完了しました</h3></br></br></br>
      <%= link_to "マイページに戻る", user_path(current_user) %>
  </div>
</div>

app/views/top/member.html.erb
<div class="row form">
  <div class="col-lg-12">
    <div class="hennsyuu">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
  </div>
</div>

app/views/users/edit.html.erb
<div id="edit_page_all" >
  <p class='mypage_black_shadow'></p>
  <div class='out_of_headder'>
        <div id='edit_area'>
             <div class="left_myapage">
              <div class="edit_all_area">
                <div class="row form">
                  <div class="col-lg-12">
                    <%= form_for current_user do |f| %>
                      <h2>登録情報</h2>
                      <div class="form-group">
                        <div class="edit_contents">
                          <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
                        </div>
                        <div class="edit_contents">
                          <%= f.text_field :family_name, placeholder: "姓", class: "form-control" %>
                        </div>
                        <div class="edit_contents">
                          <%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
                        </div>
                        <div class="edit_contents">
                          <%= f.text_field :day, placeholder: "生年月日", class: "form-control" %>
                        </div>
                        <div class="edit_contents">
                          <%= f.text_field :fav, placeholder: "お気に入りの選手", class: "form-control" %>
                        </div>
                        <div class="edit_contents">
                          <%= f.text_field :massage, placeholder: "一言", class: "form-control" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <%= f.submit "送信", class: "btn btn-primary withripple" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
             </div>
        </div>
  </div>
</div>

app/views/users/show.html.erb
<% unless current_user.full_profile? %>
  <div id="first_profile" class="header_top panel-default col-lg-12 no-profile">
    <h2>まずは、あなたのプロフィールを登録しましょう！</h2>
    <%= link_to "プロフィールを登録する", edit_user_path(current_user), { class: "btn btn-lg btn-primary withripple" } %>
  </div>

<% else %>
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
     <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">
                    <span class="title_panna">PANN<span class="red">A.</span>P</span>
                </a>
       </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
             <ul class="nav navbar-nav", id="moji">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <%= link_to "logout", destroy_user_session_path, method: :delete, id:"moji_white"%>
                </li>
              </ul>
          </div>
            <!-- /.navbar-collapse -->
  </div>
        <!-- /.container -->
</nav>








<div id="my_page_all" >
  <p class='mypage_black_shadow'></p>
  <div class='out_of_headder'>
        <div id='contents_area'>
             <div class="left_myapage">
                <h4><%= @users.family_name %>   <span><%= @users.first_name %></span></h4>
                <div class="image" style="background-image: url(<%= @users.avatar.url(:medium) %>);"></div>
                 <div class="prof_contents">
                       <div class="birth">
                        <p>birth : <%= @users.day %></p>
                      </div>
                      <div class="fav">
                        <p>fav player : <%= @users.fav %></p>
                      </div>
                      <div class="massage">
                        <p>massage : <%= @users.massage %></p>
                      </div>
                </div>
                 <% if current_user.id == @users.id %>
                    <div class="profile_edit">
                    <%= link_to "プロフィール編集", edit_user_path(current_user), {:class => "btn btn-primary withripple" }%>
                    </div>
                 <% end %>
             </div>

            <div class="right_mypage">
                    <p>Do you wanna play?</p>
                    <p>Are You Ready?</p>
                    <p>We are waiting for your attendance.</p>
                    <br>
                    <br>
                    <!-- 京都南 -->
                        <div class="row form">
                          <div class="col-lg-12">
                            <%= form_for @schedule do |f| %>
                             <div class="form-group">
                              <div class="time_table">
                                    <div class="court">
                                     <p>＜京都南＞</p>
                                     <%= link_to "空き時間の確認", "https://www.vlcm.net/rc/pc/index.php?action_CRA01_01do=true&cid=00086"  %>
                                    </div>
                                    <div class="month"><%== sprintf(f.date_select(:date, :use_month_numbers=>true, :date_separator => '%s', :start_year=>Time.now.year, :end_year => Time.now.year), '年','月') + '日'  %></div><br>

                                    <table class="demo02">
                                      <thead>
                                        <tr>
                                          <th>08:00</br><%= f.check_box :t8, placeholder: "stadium" %></th>
                                          <th>09:00</br><%= f.check_box :t9, placeholder: "stadium" %></th>
                                          <th>10:00</br><%= f.check_box :t10, placeholder: "stadium" %></th>
                                          <th>11:00</br><%= f.check_box :t11, placeholder: "stadium" %></th>
                                          <th>12:00</br><%= f.check_box :t12, placeholder: "stadium" %></th>
                                          <th>13:00</br><%= f.check_box :t13, placeholder: "stadium" %></th>
                                          <th>14:00</br><%= f.check_box :t14, placeholder: "stadium" %></th>
                                          <th>15:00</br><%= f.check_box :t15, placeholder: "stadium" %></th>
                                          <th>16:00</br><%= f.check_box :t16, placeholder: "stadium" %></th>
                                          <th>17:00</br><%= f.check_box :t17, placeholder: "stadium" %></th>
                                          <th>18:00</br><%= f.check_box :t18, placeholder: "stadium" %></th>
                                          <th>19:00</br><%= f.check_box :t19, placeholder: "stadium" %></th>
                                          <th>20:00</br><%= f.check_box :t20, placeholder: "stadium" %></th>
                                          <th>21:00</br><%= f.check_box :t21, placeholder: "stadium" %></th>
                                          <th>22:00</br><%= f.check_box :t22, placeholder: "stadium" %></th>
                                          <th>23:00</br><%= f.check_box :t23, placeholder: "stadium" %></th>

                                        </tr>
                                        </thead>
                                      </table>
                                      <div class="submit"><%= f.submit "送信", class: "btn btn-primary withripple" %></div>
                              </div>
                            <% end %>
                           </div>
                          </div>
                        </div>





                      <!-- 横大路 -->
                        <div class="row form">
                          <div class="col-lg-12">
                            <%= form_for @schedule2 do |f| %>
                             <div class="form-group">
                              <div class="time_table">
                                    <div class="court2">
                                     <p>＜横大路＞</p>
                                     <%= link_to "空き時間の確認", "https://www.vlcm.net/rc/pc/index.php?action_CRA01_01do=true&cid=00086"  %>
                                    </div>
                                      <div class="month"><%== sprintf(f.date_select(:date, :use_month_numbers=>true, :date_separator => '%s', :start_year=>Time.now.year, :end_year => Time.now.year), '年','月') + '日'  %></div><br>
                                     <table class="demo02">
                                      <thead>
                                        <tr>
                                          <th>08:00</br><%= f.check_box :t8, placeholder: "stadium" %></th>
                                          <th>09:00</br><%= f.check_box :t9, placeholder: "stadium" %></th>
                                          <th>10:00</br><%= f.check_box :t10, placeholder: "stadium" %></th>
                                          <th>11:00</br><%= f.check_box :t11, placeholder: "stadium" %></th>
                                          <th>12:00</br><%= f.check_box :t12, placeholder: "stadium" %></th>
                                          <th>13:00</br><%= f.check_box :t13, placeholder: "stadium" %></th>
                                          <th>14:00</br><%= f.check_box :t14, placeholder: "stadium" %></th>
                                          <th>15:00</br><%= f.check_box :t15, placeholder: "stadium" %></th>
                                          <th>16:00</br><%= f.check_box :t16, placeholder: "stadium" %></th>
                                          <th>17:00</br><%= f.check_box :t17, placeholder: "stadium" %></th>
                                          <th>18:00</br><%= f.check_box :t18, placeholder: "stadium" %></th>
                                          <th>19:00</br><%= f.check_box :t19, placeholder: "stadium" %></th>
                                          <th>20:00</br><%= f.check_box :t20, placeholder: "stadium" %></th>
                                          <th>21:00</br><%= f.check_box :t21, placeholder: "stadium" %></th>
                                          <th>22:00</br><%= f.check_box :t22, placeholder: "stadium" %></th>
                                          <th>23:00</br><%= f.check_box :t23, placeholder: "stadium" %></th>

                                        </tr>
                                        </thead>
                                      </table>
                                      <div class="submit"><%= f.submit "送信", class: "btn btn-primary withripple" %></div>
                              </div>
                            <% end %>
                           </div>
                          </div>
                        </div>

            </div>
            <!-- 投稿済み -->
          <div class="attend_date">
              <p>Now your Attendance</p>
            <div class="attendance_contents">
              <div class="attend_minami">
                <p>＜京都南＞</p>
                <% @attend_dates.each do |attend_date| %>
                <p><%= attend_date.date %><br>
                  <%= link_to '詳細・編集', edit_schedule_path(attend_date.id), method: :get %> /
                  <%= link_to '削除', schedule_path(attend_date.id), confirm:'削除してもよろしいですか?', method: :delete %></p>
                <% end %>
              </div>
              <div class="attend_yoko">
              <p>＜横大路＞</p>
                <% @attend_dates2.each do |attend_date2| %>
                <p><%= attend_date2.date %><br>
                  <%= link_to '詳細・編集', edit_schedule2_path(attend_date2.id), method: :get %> /
                  <%= link_to '削除', schedule2_path(attend_date2.id), confirm:'削除してもよろしいですか?', method: :delete %></p>
                <% end %>
              </div>
            </div>

          </div>
  </div>
<% end %>

app/views/users/update.html.erb
 <div class="create_all">
  <div class="send">
    <h3>プロフィールの登録が完了しました</h3></br>
     </br></br> <%= link_to "マイページに戻る", user_path(current_user) %>
  </div>
</div>